# Top-level: path to the 3D model (.obj, .fbx, .glb, or .gltf)
model = "/home/fcieslar/Downloads/luke-skywalkers-lightsaber/source/luke.fbx"

[textures]
base = "/home/fcieslar/Downloads/luke-skywalkers-lightsaber/textures/LSWBase2.png"     # albedo / diffuse
normal = "/home/fcieslar/Downloads/luke-skywalkers-lightsaber/textures/LSWNormals.png"       # normal map
roughness = "/home/fcieslar/Downloads/luke-skywalkers-lightsaber/textures/LSWRoughness.png" # roughness map
metallic = "/home/fcieslar/Downloads/luke-skywalkers-lightsaber/textures/LSAWMetallic.png"   # metallic map
